name: .NET 7.0 tests
on:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Test specflow
      uses: actions/cryptic-wizard/run-specflow-tests@v1.3.1
      with:
        test-assembly-path: Bank.Domain.Tests/bin/Release/net7.0
        test-assembly-dll: Bank.Domain.Tests.dll
        output-html: Bank.html
        framework: net7.0