name: .NET 7.0 tests
on:
  push:

jobs:
    #environment:
    #  name: github-pages
    #  url: ${{ steps.deployment.outputs.page_url }}
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Run SpecFlow Tests
      uses: cryptic-wizard/run-specflow-tests@v1.3.2
      with:
        test-assembly-path: Bank.Domain.Tests/bin/Release/net7.0
        test-assembly-dll: Bank.Domain.Tests.dll
        output-html: Bank.html
        framework: net7.0

  deploy:
    name: Deploy GP
    needs: build 
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      # Downloads the uploaded files
      with:
        name: production
        path: ./build    
    #- name: Checkout
    #    uses: actions/checkout@v3
    #- name: Setup Pages
    #  uses: actions/configure-pages@v3
    #- name: Upload artifact
    #  uses: actions/upload-pages-artifact@v1
    #  with:
    #      path: 'Bank.html'
    #- name: Deploy to GitHub Pages
    #  id: deployment
    #  uses: actions/deploy-pages@v2
